export const data = [
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
  {
    name: "James Kirk",
    description: "Ordered 12 Mac Book",
    Withdrawals: "Debit",
    Deposit: "$12,000",
    Date: "11/14/22",
    Balance: "view all",
  },
];
